resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/001ec3576ef3bda04cf5bcccdd9a00991835d1a7/snapshot.yaml

packages:
  - ./typed-transitions
  - ./typed-protocols
  - ./typed-protocols-cbor
  - ./network-mux
  - ./ouroboros-network
  - ./ouroboros-network-testing
  - ./ouroboros-consensus
  - ./io-sim
  - ./io-sim-classes

extra-deps:
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 1ebe57df3a76a8ae4e3b5a31a9b85132f71534fc
    subdirs:
      - contra-tracer
      - iohk-monitoring

  - git: https://github.com/input-output-hk/cardano-base
    commit: 64bb761664c9ca8a52a0023dc1a92c9b5b884497
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: a1de5b52c32255464564a6c5a8a9e474086e3875
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 001ec3576ef3bda04cf5bcccdd9a00991835d1a7
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-shell
    commit: efba204c14a83b9e1af9bb138c2d551fe3d7a43e
    subdirs:
      - cardano-shell

  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49

  - bimap-0.4.0
  - binary-0.8.7.0
  - generic-monoid-0.1.0.0
  - graphviz-2999.20.0.3
  - quickcheck-state-machine-0.6.0
  - splitmix-0.0.2
  - tasty-hedgehog-1.0.0.1

  # Windows only
  - Win32-2.5.4.1

nix:
  shell-file: nix/stack-shell.nix
