resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/00487726c4bc21b4744e59d913334ebfeac7d68e/snapshot.yaml

packages:
  - ./typed-protocols
  - ./typed-protocols-cbor
  - ./network-mux
  - ./ouroboros-network
  - ./ouroboros-network-testing
  - ./ouroboros-consensus
  - ./io-sim
  - ./io-sim-classes
  - ./ntp-client
  - ./Win32-network

flags:
  io-sim-classes:
    asserts: true
  network-mux:
    asserts: true
  ouroboros-network:
    asserts: true
  ouroboros-consensus:
    asserts: true

extra-deps:
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: dd30455144e11efb435619383ba84ce02aee720d
    subdirs:
      - contra-tracer

  - git: https://github.com/input-output-hk/cardano-base
    commit: 965b8b143632faea16680a195e6de57091382700
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class
      - slotting

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 6d154d16de01edf2d3ff56303b7a34cb188ed217
    subdirs:
      - byron/semantics/executable-spec
      - byron/ledger/executable-spec
      - byron/chain/executable-spec

  # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc
  - moo-1.2
  - gray-code-0.3.1

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: c62e2eeba5756898cbf59732fccd6a83a4065c18
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 00487726c4bc21b4744e59d913334ebfeac7d68e
    subdirs:
      - .
      - test

  - bimap-0.4.0
  - binary-0.8.7.0
  - bytestring-0.10.8.2
  - directory-1.3.3.0
  - filepath-1.4.2.1
  - generic-monoid-0.1.0.0
  - graphviz-2999.20.0.3
  - hedgehog-quickcheck-0.1.1
  - quickcheck-state-machine-0.6.0
  - splitmix-0.0.2
  - time-units-1.0.0
  - tasty-hedgehog-1.0.0.1
  - Unique-0.4.7.6
  - statistics-linreg-0.3
  - network-3.1.0.1

  # Windows only
  - Win32-2.6.2.0

nix:
  shell-file: nix/stack-shell.nix
