resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/71ea865408f2e03e6d6832359423546699730849/snapshot.yaml

packages:
  - ./typed-protocols
  - ./typed-protocols-examples
  - ./network-mux
  - ./ouroboros-network-framework
  - ./ouroboros-network
  - ./ouroboros-network-testing
  - ./ouroboros-consensus
  - ./ouroboros-consensus/ouroboros-consensus-test-infra
  - ./ouroboros-consensus/ouroboros-consensus-mock
  - ./ouroboros-consensus-byron
  - ./ouroboros-consensus-byron-test
  - ./ouroboros-consensus-byronspec
  - ./ouroboros-consensus-shelley
  - ./ouroboros-consensus-shelley-test
  - ./ouroboros-consensus-cardano
  - ./io-sim
  - ./io-sim-classes
  - ./ntp-client
  - ./Win32-network

flags:
  io-sim-classes:
    asserts: true
  network-mux:
    asserts: true
  ouroboros-network:
    asserts: true
    cddl: true
  ouroboros-consensus:
    asserts: true
  ouroboros-consensus-byron:
    asserts: true
  ouroboros-consensus-cardano:
    asserts: true

extra-deps:
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: d8f35c3c725be67148681227f9d64876f5909120
    subdirs:
      - contra-tracer

  - git: https://github.com/input-output-hk/cardano-base
    commit: df8687488449f71dce3d881800c21e41fe1b7fc1
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class
      - cardano-crypto-praos
      - slotting

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 9591f2d4b1915bcacd4797de563ca8a17d3b06f9
    subdirs:
      - byron/chain/executable-spec
      - byron/ledger/executable-spec
      - byron/ledger/impl
      - byron/ledger/impl/test
      - byron/crypto
      - byron/crypto/test
      - semantics/executable-spec
      - semantics/small-steps-test
      - shelley/chain-and-ledger/dependencies/non-integer
      - shelley/chain-and-ledger/executable-spec
      - shelley/chain-and-ledger/shelley-spec-ledger-test

  # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 312198a1523736181ef7ddab15958bb32a9d9052
  - moo-1.2
  - gray-code-0.3.1

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 71ea865408f2e03e6d6832359423546699730849
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-crypto/
    commit: 2547ad1e80aeabca2899951601079408becbc92c

  - bimap-0.4.0
  - binary-0.8.7.0
  - generic-monoid-0.1.0.0
  - graphviz-2999.20.1.3
  - hedgehog-quickcheck-0.1.1
  - markov-chain-usage-model-0.0.0  # Needed for `quickcheck-state-machine`
  - network-3.1.0.1
  - quickcheck-state-machine-0.7.0
  - quiet-0.2
  - sop-core-0.5.0.1
  - split-0.2.3.4
  - splitmix-0.0.2
  - statistics-linreg-0.3
  - tasty-hedgehog-1.0.0.2
  - text-1.2.4.0
  - Unique-0.4.7.6

  # Windows only
  - Win32-2.6.2.0

nix:
  shell-file: nix/stack-shell.nix
