resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/12ab51e27539c9cce042ded0c89efc0ccae6137a/snapshot.yaml

packages:
  - ./typed-transitions
  - ./typed-protocols
  - ./typed-protocols-cbor
  - ./network-mux
  - ./ouroboros-network
  - ./ouroboros-network-testing
  - ./ouroboros-consensus
  - ./io-sim
  - ./io-sim-classes

extra-deps:
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 1ebe57df3a76a8ae4e3b5a31a9b85132f71534fc
    subdirs:
      - contra-tracer
      - iohk-monitoring

  - git: https://github.com/input-output-hk/cardano-base
    commit: 1c9e91cc8cc1deecdd7696d0f7b0b74b8984aa93
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 1a791a5cc188e02d30e567d920355da2bdbb271c
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 12ab51e27539c9cce042ded0c89efc0ccae6137a
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-shell
    commit: 812a36b8d6714cf76ca3576bdac903bedd88a72b

  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49

  - bimap-0.4.0
  - binary-0.8.7.0
  - generic-monoid-0.1.0.0
  - graphviz-2999.20.0.3@sha256:cde383c356bc41136ed53cd27e0800f46dbd2185600dd0de18d66d5c49739d94
  - quickcheck-state-machine-0.6.0@sha256:3e4f8df0f6b5d415e3c8840dc75034a63e37f56f5f8cfa1035ded16345235ac4
  - splitmix-0.0.2
  - tasty-hedgehog-1.0.0.1

  # Windows only
  - Win32-2.5.4.1

nix:
  shell-file: nix/stack-shell.nix
