resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/3ac22a2fda11ca7131a011a9ea48fcbfdc26d6b3/snapshot.yaml

packages:
  - ./typed-protocols
  - ./typed-protocols-examples
  - ./network-mux
  - ./ouroboros-network-framework
  - ./ouroboros-network
  - ./ouroboros-network-testing
  - ./ouroboros-consensus
  - ./ouroboros-consensus/ouroboros-consensus-test-infra
  - ./ouroboros-consensus/ouroboros-consensus-mock
  - ./ouroboros-consensus-byron
  - ./ouroboros-consensus-byronspec
  - ./ouroboros-consensus-shelley
  - ./ouroboros-consensus-cardano
  - ./io-sim
  - ./io-sim-classes
  - ./ntp-client
  - ./Win32-network

flags:
  io-sim-classes:
    asserts: true
  network-mux:
    asserts: true
  ouroboros-network:
    asserts: true
    cddl: true
  ouroboros-consensus:
    asserts: true
  ouroboros-consensus-byron:
    asserts: true
  ouroboros-consensus-cardano:
    asserts: true

extra-deps:
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 10877fbae54aa7a4c04ae3b5d87c825a4019e9e9
    subdirs:
      - contra-tracer

  - git: https://github.com/input-output-hk/cardano-base
    commit: 742a789a520387c6cd30a4ca28bc4fc8588a41c7
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class
      - slotting

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 156086266486da710c5037c11f83d2112434926f
    subdirs:
      - byron/chain/executable-spec
      - byron/ledger/executable-spec
      - byron/semantics/executable-spec
      - shelley/chain-and-ledger/dependencies/non-integer
      - shelley/chain-and-ledger/executable-spec
      - shelley/chain-and-ledger/executable-spec/test

  # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc
  - moo-1.2
  - gray-code-0.3.1

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 53ca3542019824d169378fa36a842eb4659b7ceb
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 3ac22a2fda11ca7131a011a9ea48fcbfdc26d6b3
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-crypto/
    commit: 2547ad1e80aeabca2899951601079408becbc92c

  - git: https://github.com/advancedtelematic/quickcheck-state-machine
    commit: 2bf37003ca1c0c57e4354610d7c47da0a0e77b5c

  - bimap-0.4.0
  - binary-0.8.7.0
  - generic-monoid-0.1.0.0
  - graphviz-2999.20.0.3
  - hedgehog-quickcheck-0.1.1
  - markov-chain-usage-model-0.0.0  # Needed for `quickcheck-state-machine`
  - splitmix-0.0.2
  - tasty-hedgehog-1.0.0.2
  - Unique-0.4.7.6
  - statistics-linreg-0.3
  - network-3.1.0.1

  # Windows only
  - Win32-2.6.2.0

nix:
  shell-file: nix/stack-shell.nix
