resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/3c40edcf5bdba8721d3430d0aaaeea8770ce9bec/snapshot.yaml

packages:
  - ./typed-transitions
  - ./typed-protocols
  - ./typed-protocols-cbor
  - ./network-mux
  - ./ouroboros-network
  - ./ouroboros-network-testing
  - ./ouroboros-consensus
  - ./io-sim
  - ./io-sim-classes
  - ./ntp-client
  - ./Win32-network

extra-deps:
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 4956b32f039579a0e7e4fd10793f65b4c77d9044
    subdirs:
      - contra-tracer

  - git: https://github.com/input-output-hk/cardano-base
    commit: 057d8a9a3e751f88fc7677df5713c5ecc47a37c4
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: b404d58efb9e372305073d4ee5a660a89bb435f4
    subdirs:
      - byron/semantics/executable-spec
      - byron/ledger/executable-spec
      - byron/chain/executable-spec

  # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc
  - moo-1.2
  - gray-code-0.3.1

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 8ce6f8181c48fc2180735f0d7a0a5883065f3c8a
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 3c40edcf5bdba8721d3430d0aaaeea8770ce9bec
    subdirs:
      - .
      - test

  - bimap-0.4.0
  - binary-0.8.7.0
  - generic-monoid-0.1.0.0
  - graphviz-2999.20.0.3
  - hedgehog-quickcheck-0.1.1
  - quickcheck-state-machine-0.6.0
  - splitmix-0.0.2
  - time-units-1.0.0
  - tasty-hedgehog-1.0.0.1
  - Unique-0.4.7.6
  - statistics-linreg-0.3

  # Windows only
  - Win32-2.6.2.0

nix:
  shell-file: nix/stack-shell.nix
