resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/b25eed0ab3b6da51bc10970759d491331e56c822/snapshot.yaml

packages:
  - ./typed-transitions
  - ./typed-protocols
  - ./ouroboros-network
  - ./ouroboros-network-testing
  - ./ouroboros-consensus
  - ./io-sim
  - ./io-sim-classes

extra-deps:
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 00413dcad916a41cf392437199cfba7a2e2c76d7
    subdirs:
      - iohk-monitoring
      - contra-tracer

  - git: https://github.com/input-output-hk/cardano-base
    commit: b676160954cea07d4378ccca870a61242bc188a2
    subdirs:
      - binary
      - binary/test

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 387b54646ababbd91e26b9d7b0d33e874dbd96cb
    subdirs:
      - .
      - crypto
      - crypto/test
      - test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: d8091767addc1a51e11cb2f04392e4eb40e39b18
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-shell
    commit: 4be5660c721cae4b001187ec614ef5cf4fad8fc7

  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: e8bfc1294e088f90e5ae0b4aedbc82ee46ac5ee4

  - git: https://github.com/joelwilliamson/bimap
    commit: 997fbb38b08dec14d225d064dac05b0a85f4ceae

  - ekg-0.4.0.15
  - libyaml-0.1.0.0
  - time-units-1.0.0
  - ekg-json-0.1.0.6
  - graphviz-2999.20.0.3@sha256:cde383c356bc41136ed53cd27e0800f46dbd2185600dd0de18d66d5c49739d94
  - quickcheck-state-machine-0.6.0@sha256:3e4f8df0f6b5d415e3c8840dc75034a63e37f56f5f8cfa1035ded16345235ac4

  # The following are required only for byron-proxy
  # They will be removed when that package is factored out to its own
  # repository.
  - git: https://github.com/input-output-hk/cardano-sl
    commit: f96f3fe04719bd3b0cedc1bbaf80fa6927e937f3
    subdirs:
      - lib
      - binary
      - binary/test
      - util
      - util/test
      - infra
      - infra/test
      - core
      - core/test
      - chain
      - chain/test
      - db
      - db/test
      - crypto
      - crypto/test
      - networking

  - git: https://github.com/input-output-hk/cardano-report-server
    commit: 93f2246c54436e7f98cc363b4e0f8f1cb5e78717

  - git: https://github.com/input-output-hk/log-warper
    commit: 16246d4fbf16da7984f2a4b6c42f2ed5098182e4

  - git: https://github.com/input-output-hk/rocksdb-haskell-ng
    commit: 49f501a082d745f3b880677220a29cafaa181452

  - git: https://github.com/avieth/kademlia
    commit: 38a0575bb303804461f4b6176ca38eba81adbd79

  - git: https://github.com/serokell/network-transport
    commit: 018a50b9042c2115c3ec9c9fd5ca5f28737dd29c

  - git: https://github.com/avieth/network-transport-tcp
    commit: 2634e5e32178bb0456d800d133f8664321daa2ef

  - git: https://github.com/avieth/network-transport-inmemory
    commit: 5d8ff2b07b9df35cf61329a3d975e2c8cf95c12a

  - git: https://github.com/input-output-hk/universum.git
    commit: 7f1b2483f71cacdfd032fe447064d6e0a1df50fc

  - git: https://github.com/input-output-hk/serokell-util.git
    commit: 42586f5ea157b4a5411fbcbe41d1bf28bd942438

  - git: https://github.com/input-output-hk/ether.git
    commit: a311878ae17ed5f201421bdcd5392a24b746ff0b

  - git: https://github.com/input-output-hk/transformers-lift.git
    commit: c830bc7e7e41895e3c50488a92d34405b68b4ad8
  - aeson-options-0.1.0
  - pvss-0.2.0
  - lrucache-1.2.0.1
  - writer-cps-mtl-0.1.1.6
  - writer-cps-transformers-0.5.6.0
  - o-clock-1.0.0.1
  - ekg-wai-0.1.0.3
  # End of byron-proxy-induced dependencies.



nix:
  packages:
    - zlib
    - openssl
