resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/fe76ec64f6b45259cc407a6d840dad79ee6063b6/snapshot.yaml

packages:
  - ./typed-protocols
  - ./typed-protocols-examples
  - ./network-mux
  - ./ouroboros-network-framework
  - ./ouroboros-network
  - ./ouroboros-network-testing
  - ./ouroboros-consensus
  - ./ouroboros-consensus/ouroboros-consensus-test-infra
  - ./ouroboros-consensus/ouroboros-consensus-mock
  - ./ouroboros-consensus-byron
  - ./ouroboros-consensus-byronspec
  - ./ouroboros-consensus-cardano
  - ./io-sim
  - ./io-sim-classes
  - ./ntp-client
  - ./Win32-network

flags:
  io-sim-classes:
    asserts: true
  network-mux:
    asserts: true
  ouroboros-network:
    asserts: true
    cddl: true
  ouroboros-consensus:
    asserts: true
  ouroboros-consensus-byron:
    asserts: true
  ouroboros-consensus-cardano:
    asserts: true

extra-deps:
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 3e45d5dd4942c295f0ea4bfed7c407b914b15447
    subdirs:
      - contra-tracer

  - git: https://github.com/input-output-hk/cardano-base
    commit: f869bee9b08ba1044b1476737c9d65083e1c6c7f
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class
      - slotting

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 647cd71e3c4630488e71596f5e9c26fee598b541
    subdirs:
      - byron/semantics/executable-spec
      - byron/ledger/executable-spec
      - byron/chain/executable-spec

  # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc
  - moo-1.2
  - gray-code-0.3.1

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 026aa98773c43da4a66cff201c58a0e7a3f09b0b
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: fe76ec64f6b45259cc407a6d840dad79ee6063b6
    subdirs:
      - .
      - test

  - git: https://github.com/advancedtelematic/quickcheck-state-machine
    commit: 2bf37003ca1c0c57e4354610d7c47da0a0e77b5c

  - bimap-0.4.0
  - binary-0.8.7.0
  - generic-monoid-0.1.0.0
  - graphviz-2999.20.0.3
  - hedgehog-quickcheck-0.1.1
  - markov-chain-usage-model-0.0.0  # Needed for `quickcheck-state-machine`
  - splitmix-0.0.2
  - tasty-hedgehog-1.0.0.2
  - Unique-0.4.7.6
  - statistics-linreg-0.3
  - network-3.1.0.1

  # Windows only
  - Win32-2.6.2.0

nix:
  shell-file: nix/stack-shell.nix
