resolver: nightly-2018-11-15
packages:
- .
flags: {}
extra-package-dbs: []
allow-newer: false
nix:
    enable: false
extra-deps:
- typed-transitions/
- cborg-0.2.1.0
- serialise-0.2.1.0
- QuickCheck-2.12.6.1
