resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/001ec3576ef3bda04cf5bcccdd9a00991835d1a7/snapshot.yaml

packages:
  - ./typed-transitions
  - ./typed-protocols
  - ./typed-protocols-cbor
  - ./network-mux
  - ./ouroboros-network
  - ./ouroboros-network-testing
  - ./ouroboros-consensus
  - ./io-sim
  - ./io-sim-classes

extra-deps:
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 5b91f7a10465ae1215522a39d42df7e970ab8e8f
    subdirs:
      - contra-tracer
      - iohk-monitoring

  - git: https://github.com/input-output-hk/cardano-base
    commit: 64bb761664c9ca8a52a0023dc1a92c9b5b884497
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 11b674a10e76ab266a37225d82955fd8b1f80e27
    subdirs:
      - byron/semantics/executable-spec
      - byron/ledger/executable-spec
      - byron/chain/executable-spec

  # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc
  - moo-1.2
  - gray-code-0.3.1

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 181f69af290412abecefc07e1b26e77a453755ff
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: ad19158c7599bc5d50fe7cb0111a1488a139a381
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-shell
    commit: efba204c14a83b9e1af9bb138c2d551fe3d7a43e
    subdirs:
      - cardano-shell

  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49

  - bimap-0.4.0
  - binary-0.8.7.0
  - generic-monoid-0.1.0.0
  - graphviz-2999.20.0.3
  - hedgehog-quickcheck-0.1.1
  - quickcheck-state-machine-0.6.0
  - splitmix-0.0.2
  - tasty-hedgehog-1.0.0.1
  - Unique-0.4.7.6

  # Windows only
  - Win32-2.5.4.1

nix:
  shell-file: nix/stack-shell.nix
