steps:
  - label: 'Check Stylish Haskell'
    command: 'nix-shell --run scripts/buildkite/check-stylish.sh'
    agents:
      system: x86_64-linux

  - label: 'Check dependency tags in cabal.project are present on master branches'
    commands:
      - "nix build -f ./nix iohkNix.checkRepoTagsOnMasterBranches --arg src ./. --show-trace"
    agents:
      system: x86_64-linux
