;
; LocalStateQuery mini-protocol.
;

localStateQueryMessage = localStateQueryMessageImpl<query>

localStateQueryMessageImpl<q>
  = msgAcquire
  / msgAcquired
  / msgFailure
  / msgQuery<q>
  / msgResult
  / msgRelease
  / msgReAcquire
  / lsqMsgDone

acquireFailurePointTooOld     = 0
acquireFailurePointNotOnChain = 1

failure      = acquireFailurePointTooOld
             / acquireFailurePointNotOnChain

blockQuery      = [0, point]
getSystemStart  = [1]
getChainBlockNo = [2]
getChainPoint   = [3]

query        = blockQuery
             / getSystemStart
             / getChainBlockNo
             / getChainPoint

result       = any

msgAcquire   = [0, point]
             / [8]
             / [10]
msgAcquired  = [1]
msgFailure   = [2, failure]
msgQuery<q>  = [3, q]
msgResult    = [4, result]
msgRelease   = [5]
msgReAcquire = [6, point]
             / [9]
             / [11]
lsqMsgDone   = [7]
