;
; Peer Sharing MiniProtocol
;

peerSharingMessage = msgShareRequest
                   / msgSharePeers
                   / msgDone

msgShareRequest = [0, word8]
msgSharePeers   = [1, peerAddresses]
msgDone         = [2]

peerAddresses = [* peerAddress]

peerAddress = [0, word32, portNumber]                         ; ipv4 + portNumber
            / [1, word32, word32, word32, word32, portNumber] ; ipv6 + portNumber

portNumber = word16
