;
; TxSubmission mini-protocol v2
;

; reference implementation of the codec in :
; ouroboros-network/src/Ouroboros/Network/Protocol/TxSubmission2/Codec.hs

txSubmission2Message
    = msgInit
    ; corresponds to either MsgRequestTxIdsBlocking or
    ; MsgRequestTxIdsNonBlocking in the spec
    / msgRequestTxIds
    / msgReplyTxIds
    / msgRequestTxs
    / msgReplyTxs
    / tsMsgDone


msgInit         = [6]
msgRequestTxIds = [0, tsBlocking, txCount, txCount]
msgReplyTxIds   = [1, txIdsAndSizes ]
msgRequestTxs   = [2, txIdList ]
msgReplyTxs     = [3, txList ]
tsMsgDone       = [4]

tsBlocking      = false / true
txCount         = word16
; The codec only accepts indefinite-length lists.
txIdList        = [ *txId ]
txList          = [ *tx ]
txIdAndSize     = [txId, txSizeInBytes]
; The codec only accepts definite-length lists.
txIdsAndSizes   = [ *txIdAndSize ]
txSizeInBytes   = word32
