;
; TxSubmission mini-protocol v2
;

; reference implementation of the codec in :
; ouroboros-network/src/Ouroboros/Network/Protocol/TxSubmission2/Codec.hs

txSubmission2Message
    = msgInit
    / msgRequestTxIds
    / msgReplyTxIds
    / msgRequestTxs
    / msgReplyTxs
    / tsMsgDone


msgInit         = [6]
msgRequestTxIds = [0, tsBlocking, txCount, txCount]
msgReplyTxIds   = [1, [ *txIdAndSize] ]
msgRequestTxs   = [2, txIdList ]
msgReplyTxs     = [3, txList ]
tsMsgDone       = [4]

tsBlocking      = false / true
txCount         = word16
; The codec only accepts infinite-length list encoding for txIdList !
txIdList        = [ *txId ]
txList          = [ *tx ]
txIdAndSize     = [txId, txSizeInBytes]
txSizeInBytes   = word32
