;
; NodeToNodeVersionData, v14
;

nodeToNodeVersionData = [ networkMagic, initiatorOnlyDiffusionMode, peerSharing, query ]

; 32bit positive integer values
networkMagic = 0..2147483647
initiatorOnlyDiffusionMode = bool
; range between 0 and 1
peerSharing = 0..1
query = bool

;# import network.base as base
