;
; NodeToNodeVersionData, v14
;

nodeToNodeVersionData = [ networkMagic, initiatorOnlyDiffusionMode, peerSharing, query ]

; 32bit positive integer values
; since NodeToNodeV_16 we might encode it either as an Int (if it fits into
; `Int32`) or otherwise as an anbounded Integer - this is to support `32bit`
; architectures.
networkMagic = base.word32
initiatorOnlyDiffusionMode = bool
; range between 0 and 1
peerSharing = 0..1
query = bool

;# import network.base as base
