
; The Codecs are polymorphic in the data types for blocks, points, slot
; numbers etc. In CDDL we need concrete values so we instantiate them
; a bit arbitrarly.  See `CBOR and CDDL` in the network technical report
; https://input-output-hk.github.io/ouroboros-network/pdfs/network-spec

block  = any
header = any
tip    = any
point  = any
points = [ *point ]
txId   = any
tx     = any

; although some of our protocols are polymorphic over slots, e.g.
; `local-tx-monitor`, slots are always encoded as `word64`.
slotNo = word64

word16 = 0..65535
word32 = 0..4294967295
word64 = 0..18446744073709551615
