
; Mini-protocol codecs are polymorphic in various data types, e.g. blocks, points,
; transactions, transaction ids, etc. In CDDL we need concrete values so we
; instantiate them using `any`.  See `CBOR and CDDL` in the network
; technical report
; https://input-output-hk.github.io/ouroboros-network/pdfs/network-spec
; if you need further advise how to find concrete encoding of `Cardano` data
; types.

block  = any
header = any
tip    = any
point  = any
points = [ *point ]
txId   = any
tx     = any

; although some of our protocols are polymorphic over slots, e.g.
; `local-tx-monitor`, slots are always encoded as `word64`.
slotNo = word64

word16 = 0..65535
word32 = 0..4294967295
word64 = 0..18446744073709551615
