;
; NodeToNode Handshake, v11
;

handshakeMessage
    = msgProposeVersions
    / msgAcceptVersion
    / msgRefuse

msgProposeVersions = [0, versionTable]
msgAcceptVersion   = [1, versionNumber, nodeToNodeVersionData]
msgRefuse          = [2, refuseReason]

versionTable = { * versionNumber => nodeToNodeVersionData }

versionNumber = 11

nodeToNodeVersionData = [ networkMagic, initiatorAndResponderDiffusionMode, peerSharing ]

; range between 0 and 0xffffffff
networkMagic = 0..4294967295
initiatorAndResponderDiffusionMode = bool
; range between 0 and 2
peerSharing = 0..2

refuseReason
    = refuseReasonVersionMismatch
    / refuseReasonHandshakeDecodeError
    / refuseReasonRefused

refuseReasonVersionMismatch      = [0, [ *versionNumber ] ]
refuseReasonHandshakeDecodeError = [1, versionNumber, tstr]
refuseReasonRefused              = [2, versionNumber, tstr]

