localMessageNotificationMessage
  =
  ; corresponds to either MsgRequestMessagesBlocking or
  ; MsgRequestMessagesNonBlocking in the spec
    msgRequestMessages
  / msgReplyMessagesNonBlocking
  / msgReplyMessagesBlocking
  / msgClientDone

isBlocking = bool
hasMore = bool
msgRequestMessages          = [0, isBlocking]
; the codec only accepts indefinite lists of messages
msgReplyMessagesNonBlocking = [1, [*sig.message], hasMore]
; the codec only accepts indefinite lists of messages
msgReplyMessagesBlocking    = [2, [+sig.message], hasMore]
msgClientDone               = [3]

;# import sig as sig
