#!/usr/bin/env bash
cd "$(dirname $0)/.."
pwd

ERRORS=0

function report {
    WHAT="$1"
    let ERRORS++
    echo "Check failed: $WHAT"
}

function check-whitespace-file {
    FILE="$1"
    COUNT=$(grep -c '\s$' "$FILE")
    if [ "$COUNT" -gt 0 ]
        then
            report "trailing whitespace in $FILE"
    fi
}

# fd . ./kes-agent -e hs
for FILE in $(fd . ./kes-agent -e hs); do
    # echo "Checking: $FILE"
    check-whitespace-file "$FILE"
done

exit "$ERRORS"
