;
; KeepAlive Mini-Protocol
;

keepAliveMessage = msgKeepAlive
                 / msgKeepAliveResponse
                 / msgDone

msgKeepAlive         = [0, base.word16]
msgKeepAliveResponse = [1, base.word16]
msgDone              = [2]

;# import network.base as base
