;
; LocalTxMonitor mini-protocol.
;
;
; reference implementation of the codec in :
; ouroboros-network/src/Ouroboros/Network/Protocol/LocalTxMonitor/Codec.hs

localTxMonitorMessage
  = msgDone
  / msgAcquire
  / msgAcquired
  / msgNextTx
  / msgReplyNextTx
  / msgHasTx
  / msgReplyHasTx
  / msgGetSizes
  / msgReplyGetSizes
  / msgRelease

msgDone          = [0]

msgAcquire       = [1]
msgAcquired      = [2, slotNo]

msgAwaitAcquire  = msgAcquire
msgRelease       = [3]
msgNextTx        = [5]
msgReplyNextTx   = [6] / [6, transaction]
msgHasTx         = [7, txId]
msgReplyHasTx    = [8, bool]
msgGetSizes      = [9]
msgReplyGetSizes = [10, [word32, word32, word32]]
