name: Haskell Cabal Check

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Haskell
      uses: input-output-hk/setup-haskell@v1
      id: setup-haskell
      with:
        cabal-version: "3.8.1.0"

    - uses: actions/checkout@v3

    - name: Cabal check
      run: ./scripts/check-cabal-files.sh
